// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKSmSexvAIFP_sIRSgzHIvq-gKO0m_BAY',
    appId: '1:100443961579:web:bc7cb12834de7770bda6ae',
    messagingSenderId: '100443961579',
    projectId: 'login-3aa20',
    authDomain: 'login-3aa20.firebaseapp.com',
    storageBucket: 'login-3aa20.appspot.com',
    measurementId: 'G-65BW83H4BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQFea-6mIQncsK77cI7PPscEZTjkmkPA',
    appId: '1:100443961579:android:c474f536210e56e7bda6ae',
    messagingSenderId: '100443961579',
    projectId: 'login-3aa20',
    storageBucket: 'login-3aa20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnPklI5W3hdDfTf9PZMQ9dMGkfMEyX0w',
    appId: '1:100443961579:ios:bd43452c884d6209bda6ae',
    messagingSenderId: '100443961579',
    projectId: 'login-3aa20',
    storageBucket: 'login-3aa20.appspot.com',
    iosBundleId: 'com.example.loginScreen',
  );
}
